# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea96d7e59c18a45786df2603ef9c9ea3773d3d175f3655aafd01aa04fe61c00ca93bd44080dd668cc0daea16ac6e960b2c146c6fc4715f874401609fc52b6057

test:
  secret_key_base: bea668239cef1276508e4df5cfd8d7eab5d80965ffa1ee49f29a1f1d568d6bee7842e6a44905eb6d563a5df20cc33131e5745cf20ce74431ca79686f07951f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
